require('icons')
local status, symbols_outline = pcall(require, "symbols-outline")
if not status then
  vim.notify("没有找到 symbols-outline")
  return
end

local opts = {
  highlight_hovered_item = true,
  show_guides = true,
  auto_preview = false,
  position = 'right',
  relative_width = true,
  width = 25,
  auto_close = false,
  show_numbers = false,
  show_relative_numbers = false,
  show_symbol_details = true,
  preview_bg_highlight = 'Pmenu',
  autofold_depth = nil,
  auto_unfold_hover = true,
  fold_markers = { '', '' },
  wrap = false,
  keymaps = { -- These keymaps can be a string or a table for multiple keys
    close = { "<Esc>", "q" },
    goto_location = "<Cr>",
    focus_location = "o",
    hover_symbol = "<C-space>",
    toggle_preview = "K",
    rename_symbol = "r",
    code_actions = "a",
    fold = "h",
    unfold = "l",
    fold_all = "W",
    unfold_all = "E",
    fold_reset = "R",
  },
  lsp_blacklist = {},
  symbol_blacklist = {},
  symbols = {
    File = { icon = Icons.File, hl = "@text.uri" },
    Module = { icon = Icons.Module, hl = "@namespace" },
    Namespace = { icon = Icons.Namespace, hl = "@namespace" },
    Package = { icon = Icons.Package, hl = "@namespace" },
    Class = { icon = Icons.Class, hl = "@type" },
    Method = { icon = Icons.Method, hl = "@method" },
    Property = { icon = Icons.Property, hl = "@method" },
    Field = { icon = Icons.Field, hl = "@field" },
    Constructor = { icon = Icons.Constructor, hl = "@constructor" },
    Enum = { icon = Icons.Enum, hl = "@type" },
    Interface = { icon = Icons.Interface, hl = "@type" },
    Function = { icon = Icons.Function, hl = "@function" },
    Variable = { icon = Icons.Variable, hl = "@constant" },
    Constant = { icon = Icons.Constant, hl = "@constant" },
    String = { icon = Icons.String, hl = "@string" },
    Number = { icon = Icons.Number, hl = "@number" },
    Boolean = { icon = Icons.Boolean, hl = "@boolean" },
    Array = { icon = Icons.Array, hl = "@constant" },
    Object = { icon = Icons.Object, hl = "@type" },
    Key = { icon = Icons.Keyword, hl = "@type" },
    Null = { icon = Icons.Null, hl = "@type" },
    EnumMember = { icon = Icons.EnumMember, hl = "@field" },
    Struct = { icon = Icons.Struct, hl = "@type" },
    Event = { icon = Icons.Event, hl = "@type" },
    Operator = { icon = Icons.Operator, hl = "@operator" },
    TypeParameter = { icon = Icons.TypeParameter, hl = "@parameter" },
    Component = { icon = Icons.Component, hl = "@function" },
    Fragment = { icon = Icons.Fragment, hl = "@constant" },
  },
}

symbols_outline.setup(opts)
