-- require('lazy-plugin')
require('basic')
require('plugins')
require('keybinding')
require('autocmd')
if G.g.neovide then
  require('neovide')
end

-- 工具类
require('impatient').enable_profile()
require('config.tool.which-key')
require('config.tool.nvim-tree')
require('config.tool.telescope')
require('config.tool.comment')
require('config.tool.autopairs')
require('config.tool.toggleterm')
require('config.tool.hop')
require('config.tool.gitsigns')
require('config.tool.diffview')
require('config.tool.project')
require('config.tool.dashboard')
-- lsp
require('config.lsp.treesitter')
require('config.lsp.treesitter-twilight')
require('config.lsp.trouble')
-- require('config.dap.dap')
-- require('config.dap.dap-virtual-text')
-- require('config.dap.dap-ui')
-- require('config.dap.dap-util')
require('config.lsp.coc')
require('config.lsp.wilder')
-- 美化类
require('config.beauty.theme')
-- require('config.beauty.github-theme')
require('config.beauty.lualine')
require('config.beauty.bufferline')
-- require('config.beauty.noice')
require('config.beauty.todo-comments')
require('config.beauty.illuminate')
require('config.beauty.indent-blankline')
