require('basic')
require('plugins')
require('keybinding')
require('autocmd')

-- 工具类
require('impatient').enable_profile()
require('config.tool.which-key')
require('config.tool.nvim-tree')
require('config.tool.telescope')
require('config.tool.comment')
require('config.tool.autopairs')
require('config.tool.toggleterm')
require('config.tool.hop')
require('config.tool.gitsigns')
require('config.tool.diffview')
require('config.tool.project')
-- lsp
require('config.lsp.treesitter')
require('config.lsp.treesitter-twilight')
require('config.lsp.mason')
require('config.lsp.lspconfig')
require('config.lsp.cmp')
-- require('config.lsp.navic') -- 使用lspsaga代替
require('config.lsp.trouble')
require('config.lsp.symbol-outline') -- 有bug，preview功能暂时不能用
require('config.lsp.lspsaga')
require('config.lsp.null-ls')
require('config.dap.dap')
require('config.dap.dap-virtual-text')
require('config.dap.dap-ui')
require('config.dap.dap-util')
-- 美化类
require('config.beauty.theme')
-- require('config.beauty.github-theme')
require('config.beauty.lualine')
require('config.beauty.bufferline')
-- require('config.beauty.noice')
require('config.beauty.todo-comments')
require('config.beauty.illuminate')
require('config.beauty.indent-blankline')
